CREATE TABLE `t_tag` (
  `fid` varchar(64) NOT NULL COMMENT '主键id',
  `epc` varchar(64) NOT NULL COMMENT 'epc',
  `bill_status` int(8) DEFAULT '0' COMMENT '单据状态 0-新单  1-装箱中 2-装箱完成  3-预约送货审核中  4-同意送货  5-不同意送货   6-已发货   7-已到达目的地  8-收货中  9-   4-质检退回 6-已验收 7-差异收货',
  `bill_status` int(8) DEFAULT '0' COMMENT '单据状态 0-新单  1-送审中 1-同意 2-不同意 3-质检退回 6-已验收 7-差异收货',
  `allow_diff` int(8) DEFAULT '0' COMMENT '是否允许差异收货 0-不允许 1-允许',
  `from_location_num` varchar(64) DEFAULT 'N' COMMENT '商品移出位置,引用b_location.fid',
  `to_location_num` varchar(64) DEFAULT 'N' COMMENT '商品移入位置,引用b_location.fid',
  `container_qty` int(16) DEFAULT '0' COMMENT '容器数量',
  `package_qty` int(16) DEFAULT '0' COMMENT '包装数量',
  `transfer_qty` int(16) DEFAULT '0' COMMENT '已发货总数量 即已装箱并发出数量',
  `acceptance_qty` int(16) DEFAULT '0' COMMENT '已验收总数量 即客户验收入库总数量',
  `auditor_user` varchar(64) DEFAULT 'N' COMMENT '单据审核人 引用t_user.fid',
  `auditor_date` timestamp DEFAULT '0000-00-00 00:00:00' COMMENT '单据审核时间',
  `is_syn` varchar(64) DEFAULT 'N' COMMENT '与第三方系统同步状态 1-已同步 2-未同步 3-同步失败(失败原因可记录在remark字段)',
  `syn_date` timestamp  COMMENT '预约送货时间',
  `send_date` timestamp NULL DEFAULT NULL COMMENT '实际送货时间',
  `send_user` timestamp NULL DEFAULT NULL COMMENT '实际送货人',
  `seq` int(8) DEFAULT '0' COMMENT '显示顺序',
  `reason` varchar(2048) DEFAULT 'N' COMMENT '原因',
  `remark` varchar(256) DEFAULT 'N' COMMENT '备注',
  `attr01` varchar(256) DEFAULT 'N' COMMENT '预留字段1 --款号',
  `attr02` varchar(256) DEFAULT 'N' COMMENT '预留字段2',
  `attr03` varchar(256) DEFAULT 'N' COMMENT '预留字段3',
  `create_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `last_update` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `last_modifyer` varchar(64) NOT NULL DEFAULT 'N' COMMENT '记录最后修改人 关联b_user.fid',
  `creater` varchar(64) NOT NULL DEFAULT 'N' COMMENT '记录创建人 关联b_user.fid',
  `client_id` varchar(64) NOT NULL DEFAULT 'N' COMMENT '记录所属租户 关联b_client.fid',
  PRIMARY KEY (`fid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='工厂移仓单主表';


CREATE TABLE `f_delivery_bill_trace` (
  `fid` varchar(64) NOT NULL COMMENT '主键id',
  `bill_num` varchar(64) NOT NULL COMMENT '上游单据号',
  `bill_status` int(8) DEFAULT '0' COMMENT '单据状态 0-新单  1-装箱中 2-装箱完成  3-预约送货审核中  4-同意送货  5-不同意送货   6-已发货   7-已到达目的地  8-收货中  9-   4-质检退回 6-已验收 7-差异收货',
  `bill_status` int(8) DEFAULT '0' COMMENT '单据状态 0-新单  1-送审中 1-同意 2-不同意 3-质检退回 6-已验收 7-差异收货',
  `allow_diff` int(8) DEFAULT '0' COMMENT '是否允许差异收货 0-不允许 1-允许',
  `specific_action` varchar(64) DEFAULT 'N' COMMENT '具体操作',
  `operator` varchar(64) DEFAULT 'N' COMMENT '操作人用户名',
  `create_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间即操作时间',
  `creater` varchar(64) NOT NULL DEFAULT 'N' COMMENT '记录创建人 关联b_user.fid',
  `client_id` varchar(64) NOT NULL DEFAULT 'N' COMMENT '记录所属租户 关联b_client.fid',
  PRIMARY KEY (`fid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='工厂移仓单主表';
